### ISSUE TITLE
find_new_data=False creates a NoneType object for self.new_data

### ISSUE THREAD

**Issue by cmagness** [spacetelescope/monitor-framework#16]
in the `BaseDataModel`, `self.new_data` is set to `None` in line 56. in line 64 it should be making it empty when `find_new=False` rather than not updating it from a `NoneType`.

**Comment by jwhite3** [comment]
fix: 

```python
        self.new_data = self.get_new_data() if find_new else pd.DataFrame()
```

**Comment by jwhite3** [comment]
Actually, I lied. I think that this shouldn't be fixed here, rather at the implementation level. The implementation should handle the case where `new_data` is None rather than the framework. 

This is because fixing this at the framework level properly would require assumptions that the framework is trying to avoid.
